CREATE DATABASE IF NOT EXISTS doctor_db;
CREATE DATABASE IF NOT EXISTS patient_db;
CREATE DATABASE IF NOT EXISTS appointment_db;
CREATE DATABASE IF NOT EXISTS queue_db;
CREATE DATABASE IF NOT EXISTS report_db;
CREATE DATABASE IF NOT EXISTS auth_db;