pipeline {

    agent any

    tools {
        jdk 'jdk25'
        maven 'Maven'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/kavindideepashika26-max/appointment-service'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package -DskipTests'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    withCredentials([
                        string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')
                    ]) {
                        bat 'mvn sonar:sonar -Dsonar.projectKey=appointment -Dsonar.token=%SONAR_TOKEN%'
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t appointment .'
            }
        }
    }
}